# Generated by Django 3.1 on 2021-01-12 01:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0002_auto_20210112_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(default='media/default.jpg', max_length=255, verbose_name='images'),
        ),
    ]
